package TaskList;

public class TaskList {


}
//1. Lista zadań (Zadania + Data + Co do dokończenia / skończone)

//    Legia Warszawa -- KLIENT
//           Kolekcja lato -- ZAMÓWIENIE/KOLEKCJA
//                 02.03.2021 --- DATA DODANIA STANU
//                    50 bluz, 30 koszulek / skonczone  ---- REALIZACJA


// BAZA PROJEKTÓW - KLASA (ADMIN)
// LEGIA WARSZAWA ---> KOLEKCJA LATO ---> 100 BLUZ M, 200 KOSZULEK K ---> TERMIN REALIZACJI 2 TYG

//ALGORYTM KTÓRY ODEJMIE PRACĘ WYKONANĄ W CIĄGU DNIA OD SUMY PROJEKTU. +(FEEDBACK CZASOWY)

/*
ADMIN WRZUCA ZADANIE DLA PRACOWNIKA ----> PRACOWNIK MUSI MIEĆ LISTĘ ZADAŃ DO KTÓREJ JEST DOSTĘP Z TEJ KLASY(TASKLIST)
PRACOWNIK W LIŚCIE ZADAŃ WIDZI NOWE ZADANIE ---> PRACOWNIK MUSI MIEĆ MOŻLIWOŚĆ WYŚWIETLENIA LISTY ZADAŃ(WORKER)
PRACOWNIK JE REALIZUJE DAJE ZNAĆ ŻE ZROBIONE/NIEZROBIONE --->(WORKER)
ADMIN DOSTAJE FEEDBACK --->POWIADOMIENIE(TASK LIST) <---- W DALSZEJ PRZYSZŁOŚCI
 */