package Projects;

public class Projects {
}
/* PROJECTS
Dodawanie projektu + Klienta (LEGIA WARSZAWA(K) KOLEKCJA LATO(P))
ILOŚĆ PRODUKTU
CZAS REALIZACJI
ALGORYTM OBLICZANIA ZAROBKU FIRMY (KOSZT CAŁKOWITY PRODUKCJI VS CENA ZAMÓWIENIA(UWZGLĘDNIAJĄC TRANSPORT))
SYSTEM PROMOCYJNY(SUMA ZAMÓWIEŃ KLIENTA)
 */